"""is_active_ref_codes

Revision ID: 5e43271ac8b0
Revises: a8ea3a46798b
Create Date: 2024-03-12 21:19:52.315704

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e43271ac8b0'
down_revision: Union[str, None] = 'a8ea3a46798b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('referral_codes', sa.Column('is_active', sa.Boolean(), server_default='True', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('referral_codes', 'is_active')
    # ### end Alembic commands ###
