version: '3.8'
services:
  pdb:
    image: postgres:16.2
    container_name: db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data  # Укажите новый каталог данных
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8085:8000
    depends_on:
      - pdb

